[package]
name = "enigma"
version = "0.2.7"
edition = "2021"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
rand = "0.9.0"
chrono = "0.4.40"
log = "0.4.26"
env_logger = "0.11.7"
openssl = "0.10.71"
base64 = "0.22.1"
lazy_static = "1.5.0"
